name: material_jaspr_components
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/amadeus97/material_jaspr_components

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
